### ISSUE TITLE
Error in wow 11.0.2

### ISSUE THREAD

**Issue by Odysseas68** [Canettieri/spacer#1]
After wow update to 11.0.2 i got the following error in all spacer lua files:

 
1x TitanSpacer/TitanSpacer1.lua:8: attempt to call global 'GetAddOnMetadata' (a nil value)

[string "@TitanSpacer/TitanSpacer1.lua"]:8: in main chunk

 

Locals:

ADDON_NAME = "TitanSpacer"

L = <table> {

 more = "Larger Spacer"

 show = "Show Symbol"

}

(*temporary) = nil

(*temporary) = "TitanSpacer"

(*temporary) = "Version"

(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

**Comment by Canettieri** [comment]
Fixed, friend.
Update to the lastest version.
Thanks for the feedback!
